// Generated by view binder compiler. Do not edit!
package com.gpswalker.app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.gpswalker.app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityFavoritesBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageButton btnBack;

  @NonNull
  public final EditText etSearchFavorites;

  @NonNull
  public final FloatingActionButton fabAdd;

  @NonNull
  public final RecyclerView rvFavorites;

  private ActivityFavoritesBinding(@NonNull LinearLayout rootView, @NonNull ImageButton btnBack,
      @NonNull EditText etSearchFavorites, @NonNull FloatingActionButton fabAdd,
      @NonNull RecyclerView rvFavorites) {
    this.rootView = rootView;
    this.btnBack = btnBack;
    this.etSearchFavorites = etSearchFavorites;
    this.fabAdd = fabAdd;
    this.rvFavorites = rvFavorites;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityFavoritesBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityFavoritesBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_favorites, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityFavoritesBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnBack;
      ImageButton btnBack = ViewBindings.findChildViewById(rootView, id);
      if (btnBack == null) {
        break missingId;
      }

      id = R.id.etSearchFavorites;
      EditText etSearchFavorites = ViewBindings.findChildViewById(rootView, id);
      if (etSearchFavorites == null) {
        break missingId;
      }

      id = R.id.fabAdd;
      FloatingActionButton fabAdd = ViewBindings.findChildViewById(rootView, id);
      if (fabAdd == null) {
        break missingId;
      }

      id = R.id.rvFavorites;
      RecyclerView rvFavorites = ViewBindings.findChildViewById(rootView, id);
      if (rvFavorites == null) {
        break missingId;
      }

      return new ActivityFavoritesBinding((LinearLayout) rootView, btnBack, etSearchFavorites,
          fabAdd, rvFavorites);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
