// Generated by view binder compiler. Do not edit!
package com.gpswalker.app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.SwitchCompat;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.gpswalker.app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySettingsBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final ImageButton btnBack;

  @NonNull
  public final Button btnSignOut;

  @NonNull
  public final Button btnTestConnection;

  @NonNull
  public final SeekBar seekStepLength;

  @NonNull
  public final SwitchCompat switchHealthSync;

  @NonNull
  public final TextView tvEmail;

  @NonNull
  public final TextView tvHcStatus;

  @NonNull
  public final TextView tvMovementSpeed;

  @NonNull
  public final TextView tvStepLength;

  @NonNull
  public final TextView tvSyncStatus;

  private ActivitySettingsBinding(@NonNull ScrollView rootView, @NonNull ImageButton btnBack,
      @NonNull Button btnSignOut, @NonNull Button btnTestConnection,
      @NonNull SeekBar seekStepLength, @NonNull SwitchCompat switchHealthSync,
      @NonNull TextView tvEmail, @NonNull TextView tvHcStatus, @NonNull TextView tvMovementSpeed,
      @NonNull TextView tvStepLength, @NonNull TextView tvSyncStatus) {
    this.rootView = rootView;
    this.btnBack = btnBack;
    this.btnSignOut = btnSignOut;
    this.btnTestConnection = btnTestConnection;
    this.seekStepLength = seekStepLength;
    this.switchHealthSync = switchHealthSync;
    this.tvEmail = tvEmail;
    this.tvHcStatus = tvHcStatus;
    this.tvMovementSpeed = tvMovementSpeed;
    this.tvStepLength = tvStepLength;
    this.tvSyncStatus = tvSyncStatus;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySettingsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySettingsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_settings, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySettingsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnBack;
      ImageButton btnBack = ViewBindings.findChildViewById(rootView, id);
      if (btnBack == null) {
        break missingId;
      }

      id = R.id.btnSignOut;
      Button btnSignOut = ViewBindings.findChildViewById(rootView, id);
      if (btnSignOut == null) {
        break missingId;
      }

      id = R.id.btnTestConnection;
      Button btnTestConnection = ViewBindings.findChildViewById(rootView, id);
      if (btnTestConnection == null) {
        break missingId;
      }

      id = R.id.seekStepLength;
      SeekBar seekStepLength = ViewBindings.findChildViewById(rootView, id);
      if (seekStepLength == null) {
        break missingId;
      }

      id = R.id.switchHealthSync;
      SwitchCompat switchHealthSync = ViewBindings.findChildViewById(rootView, id);
      if (switchHealthSync == null) {
        break missingId;
      }

      id = R.id.tvEmail;
      TextView tvEmail = ViewBindings.findChildViewById(rootView, id);
      if (tvEmail == null) {
        break missingId;
      }

      id = R.id.tvHcStatus;
      TextView tvHcStatus = ViewBindings.findChildViewById(rootView, id);
      if (tvHcStatus == null) {
        break missingId;
      }

      id = R.id.tvMovementSpeed;
      TextView tvMovementSpeed = ViewBindings.findChildViewById(rootView, id);
      if (tvMovementSpeed == null) {
        break missingId;
      }

      id = R.id.tvStepLength;
      TextView tvStepLength = ViewBindings.findChildViewById(rootView, id);
      if (tvStepLength == null) {
        break missingId;
      }

      id = R.id.tvSyncStatus;
      TextView tvSyncStatus = ViewBindings.findChildViewById(rootView, id);
      if (tvSyncStatus == null) {
        break missingId;
      }

      return new ActivitySettingsBinding((ScrollView) rootView, btnBack, btnSignOut,
          btnTestConnection, seekStepLength, switchHealthSync, tvEmail, tvHcStatus, tvMovementSpeed,
          tvStepLength, tvSyncStatus);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
