// Generated by view binder compiler. Do not edit!
package com.gpswalker.app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.gpswalker.app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.osmdroid.views.MapView;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final ImageButton btnCircle;

  @NonNull
  public final ImageButton btnHexagon;

  @NonNull
  public final Button btnOpenPikmin;

  @NonNull
  public final Button btnPause;

  @NonNull
  public final Button btnResumeMove;

  @NonNull
  public final ImageButton btnSquare;

  @NonNull
  public final Button btnStart;

  @NonNull
  public final Button btnStop;

  @NonNull
  public final Button btnSyncFit;

  @NonNull
  public final LinearLayout controlPanel;

  @NonNull
  public final MapView mapView;

  @NonNull
  public final LinearLayout navFavorites;

  @NonNull
  public final LinearLayout navMap;

  @NonNull
  public final LinearLayout navSettings;

  @NonNull
  public final LinearLayout runningPanel;

  @NonNull
  public final EditText searchInput;

  @NonNull
  public final LinearLayout searchResultsLayout;

  @NonNull
  public final TextView tvDistance;

  @NonNull
  public final TextView tvHealthStatus;

  @NonNull
  public final TextView tvRunningTime;

  @NonNull
  public final TextView tvSpeed;

  @NonNull
  public final TextView tvSteps;

  private ActivityMainBinding(@NonNull FrameLayout rootView, @NonNull ImageButton btnCircle,
      @NonNull ImageButton btnHexagon, @NonNull Button btnOpenPikmin, @NonNull Button btnPause,
      @NonNull Button btnResumeMove, @NonNull ImageButton btnSquare, @NonNull Button btnStart,
      @NonNull Button btnStop, @NonNull Button btnSyncFit, @NonNull LinearLayout controlPanel,
      @NonNull MapView mapView, @NonNull LinearLayout navFavorites, @NonNull LinearLayout navMap,
      @NonNull LinearLayout navSettings, @NonNull LinearLayout runningPanel,
      @NonNull EditText searchInput, @NonNull LinearLayout searchResultsLayout,
      @NonNull TextView tvDistance, @NonNull TextView tvHealthStatus,
      @NonNull TextView tvRunningTime, @NonNull TextView tvSpeed, @NonNull TextView tvSteps) {
    this.rootView = rootView;
    this.btnCircle = btnCircle;
    this.btnHexagon = btnHexagon;
    this.btnOpenPikmin = btnOpenPikmin;
    this.btnPause = btnPause;
    this.btnResumeMove = btnResumeMove;
    this.btnSquare = btnSquare;
    this.btnStart = btnStart;
    this.btnStop = btnStop;
    this.btnSyncFit = btnSyncFit;
    this.controlPanel = controlPanel;
    this.mapView = mapView;
    this.navFavorites = navFavorites;
    this.navMap = navMap;
    this.navSettings = navSettings;
    this.runningPanel = runningPanel;
    this.searchInput = searchInput;
    this.searchResultsLayout = searchResultsLayout;
    this.tvDistance = tvDistance;
    this.tvHealthStatus = tvHealthStatus;
    this.tvRunningTime = tvRunningTime;
    this.tvSpeed = tvSpeed;
    this.tvSteps = tvSteps;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnCircle;
      ImageButton btnCircle = ViewBindings.findChildViewById(rootView, id);
      if (btnCircle == null) {
        break missingId;
      }

      id = R.id.btnHexagon;
      ImageButton btnHexagon = ViewBindings.findChildViewById(rootView, id);
      if (btnHexagon == null) {
        break missingId;
      }

      id = R.id.btnOpenPikmin;
      Button btnOpenPikmin = ViewBindings.findChildViewById(rootView, id);
      if (btnOpenPikmin == null) {
        break missingId;
      }

      id = R.id.btnPause;
      Button btnPause = ViewBindings.findChildViewById(rootView, id);
      if (btnPause == null) {
        break missingId;
      }

      id = R.id.btnResumeMove;
      Button btnResumeMove = ViewBindings.findChildViewById(rootView, id);
      if (btnResumeMove == null) {
        break missingId;
      }

      id = R.id.btnSquare;
      ImageButton btnSquare = ViewBindings.findChildViewById(rootView, id);
      if (btnSquare == null) {
        break missingId;
      }

      id = R.id.btnStart;
      Button btnStart = ViewBindings.findChildViewById(rootView, id);
      if (btnStart == null) {
        break missingId;
      }

      id = R.id.btnStop;
      Button btnStop = ViewBindings.findChildViewById(rootView, id);
      if (btnStop == null) {
        break missingId;
      }

      id = R.id.btnSyncFit;
      Button btnSyncFit = ViewBindings.findChildViewById(rootView, id);
      if (btnSyncFit == null) {
        break missingId;
      }

      id = R.id.controlPanel;
      LinearLayout controlPanel = ViewBindings.findChildViewById(rootView, id);
      if (controlPanel == null) {
        break missingId;
      }

      id = R.id.mapView;
      MapView mapView = ViewBindings.findChildViewById(rootView, id);
      if (mapView == null) {
        break missingId;
      }

      id = R.id.navFavorites;
      LinearLayout navFavorites = ViewBindings.findChildViewById(rootView, id);
      if (navFavorites == null) {
        break missingId;
      }

      id = R.id.navMap;
      LinearLayout navMap = ViewBindings.findChildViewById(rootView, id);
      if (navMap == null) {
        break missingId;
      }

      id = R.id.navSettings;
      LinearLayout navSettings = ViewBindings.findChildViewById(rootView, id);
      if (navSettings == null) {
        break missingId;
      }

      id = R.id.runningPanel;
      LinearLayout runningPanel = ViewBindings.findChildViewById(rootView, id);
      if (runningPanel == null) {
        break missingId;
      }

      id = R.id.searchInput;
      EditText searchInput = ViewBindings.findChildViewById(rootView, id);
      if (searchInput == null) {
        break missingId;
      }

      id = R.id.searchResultsLayout;
      LinearLayout searchResultsLayout = ViewBindings.findChildViewById(rootView, id);
      if (searchResultsLayout == null) {
        break missingId;
      }

      id = R.id.tvDistance;
      TextView tvDistance = ViewBindings.findChildViewById(rootView, id);
      if (tvDistance == null) {
        break missingId;
      }

      id = R.id.tvHealthStatus;
      TextView tvHealthStatus = ViewBindings.findChildViewById(rootView, id);
      if (tvHealthStatus == null) {
        break missingId;
      }

      id = R.id.tvRunningTime;
      TextView tvRunningTime = ViewBindings.findChildViewById(rootView, id);
      if (tvRunningTime == null) {
        break missingId;
      }

      id = R.id.tvSpeed;
      TextView tvSpeed = ViewBindings.findChildViewById(rootView, id);
      if (tvSpeed == null) {
        break missingId;
      }

      id = R.id.tvSteps;
      TextView tvSteps = ViewBindings.findChildViewById(rootView, id);
      if (tvSteps == null) {
        break missingId;
      }

      return new ActivityMainBinding((FrameLayout) rootView, btnCircle, btnHexagon, btnOpenPikmin,
          btnPause, btnResumeMove, btnSquare, btnStart, btnStop, btnSyncFit, controlPanel, mapView,
          navFavorites, navMap, navSettings, runningPanel, searchInput, searchResultsLayout,
          tvDistance, tvHealthStatus, tvRunningTime, tvSpeed, tvSteps);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
