// Generated by view binder compiler. Do not edit!
package com.gpswalker.app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.gpswalker.app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class DialogAddFavoriteBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final EditText etCoordinates;

  @NonNull
  public final EditText etPlaceName;

  private DialogAddFavoriteBinding(@NonNull LinearLayout rootView, @NonNull EditText etCoordinates,
      @NonNull EditText etPlaceName) {
    this.rootView = rootView;
    this.etCoordinates = etCoordinates;
    this.etPlaceName = etPlaceName;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogAddFavoriteBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogAddFavoriteBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_add_favorite, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogAddFavoriteBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.etCoordinates;
      EditText etCoordinates = ViewBindings.findChildViewById(rootView, id);
      if (etCoordinates == null) {
        break missingId;
      }

      id = R.id.etPlaceName;
      EditText etPlaceName = ViewBindings.findChildViewById(rootView, id);
      if (etPlaceName == null) {
        break missingId;
      }

      return new DialogAddFavoriteBinding((LinearLayout) rootView, etCoordinates, etPlaceName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
